import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useRef, useState } from "react";
import emailjs from "@emailjs/browser";

export default function Home() {
  const form = useRef();
  const [requestResult, setRequestResult] = useState<string>("");
  const [isSending, setisSending] = useState<boolean>(false);

  const sendEmail = (e) => {
    e.preventDefault();

    emailjs
      .sendForm(
        "service_fu3e81h",
        "template_awekiyp",
        form.current,
        "SSkG8ICAmWQVcuQ4B"
      )
      .then(
        (result) => {
          console.log(result.text);
          setisSending(false);
          e.target.reset();
          setRequestResult("Successful");
          setTimeout(() => {
            setRequestResult("");
          }, 3000);
        },
        (error) => {
          console.log(error.text);
          console.log("Error");
          setRequestResult("Failed");
          setisSending(false);
        }
      );
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Email Js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-blue-800 h-screen pt-16 w-full">
        <form
          ref={form}
          onSubmit={sendEmail}
          className="bg-white p-8 max-w-[500px] m-auto  ">
          <h1 className="font-semibold text-3xl text-center">Form</h1>
          <input
            type="text"
            placeholder="Enter Name"
            name="name"
            className="border-b border-gray-300 w-full outline-none my-8"
          />

          <input
            type="email"
            name="email"
            placeholder="Enter Email"
            className="border-b border-gray-300 w-full outline-none"
          />

          <textarea
            placeholder="Enter Name"
            name="message"
            className="border border-gray-300 w-full outline-none my-8 h-[200px]"
          />

          <input
            type="submit"
            value="Submit"
            className="bg-black text-white px-8 py-3 rounded-xl"
          />
        </form>
      </div>
    </div>
  );
}
